"""Bundle the public aggregate JSON files into assets/app/data.js for the D3 film.

The film reads `window.CS201` so it works from file:// and GitHub Pages without fetch.
Only the three published aggregate files are bundled; nothing private is read.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'homework': ROOT / 'data/summary.json',
    'midterm': ROOT / 'data/midterm-summary.json',
    'platform': ROOT / 'data/platform-summary.json',
}


def main():
    bundle = {key: json.loads(path.read_text()) for key, path in SOURCES.items()}
    body = json.dumps(bundle, ensure_ascii=False, separators=(',', ':'))
    out = ROOT / 'assets/app/data.js'
    out.write_text(
        '// Generated by scripts/build_app_data.py from data/*.json. Do not edit by hand.\n'
        f'window.CS201 = {body};\n'
    )
    print(f'wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)')


if __name__ == '__main__':
    main()
