"""Build the public, static progress-check page from the same aggregate evidence."""
from html import escape as e
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
d=json.loads((ROOT/'data/summary.json').read_text())
def table(headers,rows,caption):
    return '<div class="table-scroll"><table><caption>'+e(caption)+'</caption><thead><tr>'+''.join('<th scope="col">'+e(str(h))+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+e(str(v))+'</td>' for v in r)+'</tr>' for r in rows)+'</tbody></table></div>'
def figure(name,alt,caption):
    return f'<figure><picture><source media="(max-width: 900px)" srcset="assets/figures/{name}-mobile.svg"><img src="assets/figures/{name}.svg" alt="{e(alt)}" loading="lazy"></picture><figcaption>{caption}</figcaption></figure><div class="downloads"><a href="assets/figures/{name}.png" download>Download PNG ↗</a><a href="assets/figures/{name}.svg" download>Download SVG ↗</a><a href="assets/figures/{name}.pdf" download>Download PDF ↗</a></div>'
counts=table(['Homework','Problems','Submitters','Submissions','Minimum','Q1','Median','Q3','Maximum'],[[a['homework'],a['problems'],a['all_attempts']['n'],a['submissions'],*[f"{a['all_attempts'][k]:g}" for k in ['min','q1','median','q3','max']]] for a in d['assignments']], 'Window-based attempt counts; one observation per student and homework with ≥1 submission.')
scoretable=table(['Homework','Problem','Name','Attempters','First mean','Best mean','Difference (pp)'],[[r['homework'],f"P{r['problem_order']}",r['problem_name'],r['n'],f"{r['first']:.2f}",f"{r['best']:.2f}",f"{r['gain']:.2f}"] for r in d['score_progression']],'Per-problem means of normalized scores, sorted by difference within each homework.')
caltable=table(['Date','Hours (Beijing)','Status','Submissions','Distinct contributors'],[[c['date'],f"{c['hour']:02d}:00–{c['hour']+4:02d}:00",c['state'],c['submissions'] if c['submissions'] is not None else '—',c['contributors'] if c['contributors'] is not None else '—'] for c in d['calendar']], 'Public four-hour calendar cells. Suppressed cells have 1–4 contributors. Inactive cells have no configured homework window.')
windows=table(['Homework','Opens (UTC+08)','Configured deadline (UTC+08)','Outside-window records'],[[a['homework'],a['start_local'][:16].replace('T',' '),a['end_local'][:16].replace('T',' '),a['outside_window']] for a in d['assignments']], 'Configured assignment windows. Individual extensions have not been incorporated.')
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Four actual-data visualizations of CS201 homework submission timing, retries, and score progression."><title>CS201 Homework Submission Patterns</title><link rel="stylesheet" href="styles.css"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="#">CS201 / PROCESS NOTES</a><nav aria-label="Main navigation"><a href="#timing">Figures</a><a href="#dataset">Dataset</a><a href="#evaluation">Evaluation</a></nav></header><main id="main"><section class="hero"><p class="eyebrow">STATS 401 · FINAL PROJECT · IN-CLASS PROGRESS CHECK</p><h1>Similar scores.<br><em>Different paths.</em></h1><p class="lead">CS201 Homework Submission Patterns:<br>Timing, Retries, and Score Progression</p><p class="intro">When homework scores cluster near full marks, the submission process still varies. We examine when students submit, how often they retry, and how first scores compare with the best scores they reach.</p><p class="byline">Zaozao Wang &amp; Zhengxiang Liu · Snapshot: 20 September 2026</p><div class="stats"><div><strong>2,101</strong><span>submissions within homework windows</span></div><div><strong>39 / 42</strong><span>roster members with window submissions</span></div><div><strong>3</strong><span>homeworks · 23 problem slots</span></div></div><p class="status">Current milestone: four implemented static figures using actual project data. Interactions and the user evaluation below are planned.</p></section>
<section class="opening"><p class="eyebrow">THE QUESTION</p><h2>What do near-perfect scores leave out?</h2><p>In the <code>participation_mode=0</code> records, 37/40 HW1 scores, 33/39 HW2 scores and 37/39 HW3 scores are 100. The formal interpretation of this participation field still needs confirmation. These records motivate a process-focused analysis; they are not a substitute for verifying the official grading rules.</p><p>Within the observation windows, <strong>178 submissions earned partial credit</strong>. The figures below describe that recorded process. Submission gaps are not measured study time, and more attempts do not establish greater effort or better learning.</p></section>
<section class="chart-section" id="timing"><div class="section-heading"><span class="number">01</span><div><p class="eyebrow">TIMING</p><h2>Activity volume and participation<br>tell different stories.</h2></div></div><p class="reading">Across the full day on <strong>29 August, 233 submissions came from 14 students</strong>. In the visible 12:00–16:00 cell, 153 submissions came from 12 students. A busy period need not mean the whole class was working then.</p>'''
html+=figure('01-calendar','Paired date-by-time heatmaps show submission counts and distinct contributors. August 29, 12–16 Beijing time has 153 submissions from 12 contributors.','Both panels describe the same windows but have separate color scales. Public cells cover four hours; 51 positive cells with fewer than five contributors are masked. Blank light cells are zero, hatched cells are suppressed, and gray cells are outside all homework windows. A separate full-hour version is retained locally.')
html+='<details><summary>Accessible data table · calendar</summary>'+caltable+'</details><div class="plan"><h3>Planned interaction / animation</h3><p>Filter by HW1, HW2 or HW3; switch between submissions and distinct contributors; select a day to inspect its time distribution. These controls will distinguish broad participation from repeated attempts. The public view will retain suppression after filtering. No animation is needed to read timing accurately.</p></div></section>'
html+='''<section class="chart-section" id="retries"><div class="section-heading"><span class="number">02</span><div><p class="eyebrow">RETRIES</p><h2>A typical count hides a wide range.</h2></div></div><p class="reading">Median counts are <strong>12.5, 13 and 14</strong>, but observed ranges are 8–98, 3–62 and 7–108. The distributions include only students who submitted within each homework window. The underlying tasks also differ: HW1 and HW2 have eight problems; HW3 has seven.</p>'''
html+=figure('02-attempts','Three boxplots of student submission counts. HW1 median 12.5 and range 8–98; HW2 median 13 and range 3–62; HW3 median 14 and range 7–108.','Whiskers show the observed minimum and maximum, not 1.5×IQR. Boxes use inclusive quartiles. No individual student points are published. Different problem counts and difficulty limit comparisons across homeworks.')
html+='<details><summary>Accessible data table · attempt counts</summary>'+counts+'</details><div class="plan"><h3>Planned interaction / animation</h3><p>Switch between all attempts and attempts through the first accepted submission for each student–problem pair, including that successful attempt. Retain all observed attempts for pairs that never reach acceptance. Animate the box transition briefly, with a reduced-motion option, to show how <strong>318 post-acceptance submissions</strong> affect the distributions. Acceptance uses the recorded AC verdict; it is distinct from normalized full score.</p></div></section>'
html+='''<section class="chart-section" id="scores"><div class="section-heading"><span class="number">03</span><div><p class="eyebrow">SCORE PROGRESSION</p><h2>The endpoint does not tell<br>the whole story.</h2></div></div><p class="reading"><strong>HW3 TicTacToe</strong> has the largest first-to-best difference: its 39 attempters average 37.95 on their first submission and 100 for their best observed score, a difference of 62.05 percentage points. Both means use the same students.</p>'''
html+=figure('03-score-progression','Dumbbell chart of 23 homework problem slots. First scores use open circles and best scores use diamonds. HW3 TicTacToe has the largest mean difference, 62.05 percentage points.','Scores are normalized within each homework problem. Endpoints are means across the same attempters, including students who submit only once. Best scores increase or stay constant by construction; the gap is not an estimate of learning caused by retrying. Problem labels omit assignment/exercise prefixes; full names appear in the table.')
html+='<details><summary>Accessible data table · first and best scores</summary>'+scoretable+'</details><div class="plan"><h3>Planned interaction / animation</h3><p>Filter by homework and switch the best-score endpoint between the first two attempts, first three attempts and all observed attempts. Keep the original set of attempters: for students with fewer attempts, use their best observed score so far. A short endpoint transition will reveal where gains accumulate without changing the comparison cohort.</p></div></section>'

attempttable=table(['Homework','Attempt','Mean actual score (%)','Submission events (N)','Distinct students (S)'],
    [[r['homework'],r['attempt'],f"{r['mean_score']:.2f}",r['submissions'],r['contributors']]
     for r in d['attempt_score_series'] if r['state']=='visible'],
    'Each point includes only pairs reaching that attempt. Fewer than five students: point withheld; no score carried forward.')
html+='''<section class="chart-section" id="attempt-scores"><div class="section-heading"><span class="number">04</span><div><p class="eyebrow">MEAN SCORE BY ATTEMPT</p><h2>What does each successive<br>submission actually score?</h2></div></div><p class="reading">Each point averages the <strong>actual score on the nth submission to the same homework problem</strong>, normalized to 0–100. HW1, HW2 and HW3 are separate panels. This is not a running-best curve.</p><p>For HW1, the first-attempt mean is 76.93 across 304 student–problem events from 38 students; the second-attempt mean is 64.53 across 106 events from 34 students. Students who finish a problem and stop submitting no longer contribute to its later points. <strong>A lower later mean does not mean the same group became worse.</strong></p>'''
html+=figure('04-attempt-scores','Three panels show mean actual normalized score at each within-problem attempt number. Sample sizes decrease as fewer student–problem pairs continue submitting.','N counts submitted student–problem events; S counts distinct students. All observed attempts are eligible, including post-acceptance attempts. Each event has equal weight, so a student retrying several problems contributes several events. Points with fewer than five students are withheld; gray tails indicate withheld positions within the displayed range. There are no carried-forward values, confidence bands or claims of causality.')
html+='<details><summary>Accessible data table · actual score by attempt</summary>'+attempttable+'</details><div class="plan"><h3>Planned interaction / animation</h3><p>Filter by problem or homework, inspect mean/N/S on hover, and compare actual-attempt scores with cumulative-best summaries under explicitly different cohort definitions. Keep sample counts visible during transitions and apply the minimum-contributor rule after filtering. The purpose is to expose changing sample composition, not imply individual learning trajectories.</p></div></section>'

html+='''<section id="dataset" class="methods"><p class="eyebrow">DATASET &amp; PROCESSING</p><h2>From private event logs<br>to reproducible summaries.</h2><div class="two-col"><div><h3>Raw dataset · private</h3><p>A read-only CS201 course export contains nine tables: metadata, course, roster, assignments, submissions, assignment–problem mappings, problems, participations and submission–assignment links. The scoped export contains 42 non-staff/non-superuser roster members and 2,343 submission events from 40 members, across seven assignments. It excludes source code and direct identity fields from the analysis bundle. Pseudonyms remain private.</p><p>The export is a snapshot, not a live connection. The website never queries the production server. Raw logs, individual scores and the linkage key are not published.</p></div><div><h3>Processed dataset · public</h3><p>The three homework assignments contain 2,171 submission events. Restricting each event to its own configured homework opening and deadline retains <strong>2,101 events from 39 students</strong>; 70 events outside these windows remain in the raw export but are excluded from these figures.</p><p>The published <a href="data/summary.json">aggregate JSON</a> contains masked time bins, homework count distributions and per-problem score means. It contains no student identifiers or event-level records. Public bins require at least five contributors; suppression reduces disclosure but is not a formal privacy guarantee.</p></div></div><h3>Completed processing</h3><ol><li>Confirmed the CS201 roster scope, removed staff/superuser accounts, and recorded the user's confirmation that no extra accounts need exclusion.</li><li>Checked unique keys and join coverage for submissions, assignment links and problem maxima. Repeated attempts remain separate events; they are not treated as accidental duplicates.</li><li>Converted UTC timestamps to Asia/Shanghai before assigning dates or time bins; selected the configured homework windows below.</li><li>Validated finite scores and positive maxima, then calculated <code>100 × assignment_submission_score / problem_max_points</code>. Raw cross-problem scores are not mixed.</li><li>Sorted student–homework–problem events by timestamp and submission ID, computed first and running-best scores, and aggregated over the same attempters.</li><li>Created summary boxplots and masked calendar bins. Zero-submitters remain in the roster count but are excluded from attempt-count distributions.</li></ol>'''+windows+'''<p class="caution">Scope limitations: configured deadlines may differ from individual extensions. These are recorded submissions, not all work a student performed. No exam outcomes, AI-platform logs or causal claims are part of the current analysis.</p><p><a href="docs/methods.md">Detailed methods and data dictionary ↗</a> · <a href="https://github.com/Cis-jujube/STATS-401-Final-Project">Source and reproduction instructions ↗</a></p></section>
<section id="evaluation" class="evaluation"><p class="eyebrow">EVALUATION PLAN · NOT YET RUN</p><h2>Can readers answer the questions<br>without overinterpreting the data?</h2><p>We plan a formative study with approximately five classmates or teaching assistants. Participants will use the static page first, then repeat comparable tasks after interactions are implemented. We will rotate task order, use think-aloud observation, and avoid treating this small convenience sample as a representative experiment.</p><div class="table-scroll"><table><caption>Tasks, evaluation criteria and feedback to collect</caption><thead><tr><th scope="col">Task</th><th scope="col">What we evaluate</th><th scope="col">What we collect</th></tr></thead><tbody><tr><td>Find a visible submission peak and compare its two panels.</td><td>Reading dates, color scales, counts vs distinct people, and suppression.</td><td>Answer correctness, completion time, help requests and misread cells.</td></tr><tr><td>Compare the medians and ranges of the three homeworks.</td><td>Understanding boxes, min–max whiskers, denominators and unequal problem counts.</td><td>Correctness, time, confidence (1–5), and confusing labels.</td></tr><tr><td>Identify the largest first-to-best score difference.</td><td>Reading endpoints, normalized scores and the same-cohort comparison.</td><td>Selected problem, estimated gap, time and explanation.</td></tr><tr><td>Read the first and second attempt means and their N/S rows.</td><td>Distinguishing actual-attempt scores from running best and recognizing cohort attrition.</td><td>Correctness, time and explanation of why a falling mean need not indicate individual decline.</td></tr><tr><td>Explain what more attempts and longer submission gaps can tell us.</td><td>Whether the page prevents effort, study-time and causal-learning misconceptions.</td><td>Open-ended explanation, misconception notes and wording suggestions.</td></tr></tbody></table></div><p>Before testing, we will derive an answer key from the aggregate JSON. We will summarize task accuracy, median completion time and repeated points of confusion, then revise labels, legends and interaction defaults. Feedback will be recorded without names; no evaluation results are claimed at this milestone.</p></section>
<section class="next"><p class="eyebrow">FUTURE EXTENSION / RETRY INTERVALS</p><h2>Does the next attempt set a new best?</h2><p>Explore adjacent submissions within the same student, homework and problem, restricted to cases where the prior best is below full credit and a next attempt is observed. Compare the proportion exceeding the historical best across retry-gap bins, reporting both pair counts and distinct contributors.</p><p>Stratify by problem, prior score and prior verdict. Sparse bins will be combined or withheld. Any uncertainty estimates must account for repeated observations within students. A retry gap is elapsed clock time, not study duration; this remains an exploratory association. This retry-interval analysis is separate from the four completed static visualizations.</p></section><section class="next" id="midterm-plan"><p class="eyebrow">FUTURE WORK / MIDTERM COMPARISON</p><h2>Add exam outcomes<br>when the data become available.</h2><p>After we obtain authorized midterm examination scores, we plan to add comparisons between pre-exam homework submission patterns and exam performance. The current export contains no midterm scores, and no exam-related findings are claimed.</p><p>We will confirm the exam scale, cohort and missing-score rules, match records locally with private pseudonymous identifiers, and use only homework activity observed before the exam. Candidate comparisons include per-student attempt counts, timing summaries and normalized score progression versus the midterm score. We will report the matched sample size and missingness, assess ceiling effects and outliers, and use descriptive comparisons or exploratory associations rather than causal claims.</p><p>Individual grades and linkage keys will stay private; public outputs will use appropriately aggregated results. Exam difficulty, prior knowledge and problem difficulty may explain associations, so the extension will not treat submission intervals as study time or claim that more attempts cause higher exam scores.</p></section></main><footer><p>CS201 Homework Submission Patterns · Zaozao Wang &amp; Zhengxiang Liu</p><p>Actual project data · Static progress check · 20 Sep 2026</p><p>Figure style follows <a href="https://github.com/ChenLiu-1996/figures4papers/tree/main/scientific-figure-making">figures4papers / Scientific Figure Making</a>; generated with Matplotlib.</p><a href="proposal.md">Original proposal (historical, superseded scope)</a></footer></body></html>'''
(ROOT/'index.html').write_text(html.replace('><', '>\n<')+'\n')
