"""Bundle the public aggregate JSON files into assets/app/data.js for the D3 film.

The film reads `window.CS201` so it works from file:// and GitHub Pages without fetch.
Only the three published aggregate files are bundled; nothing private is read.

The shared figure manifest (assets/app/figures.json: figure identities, evidence anchors,
downloads and Core/Showcase route membership) is written to assets/app/figures.js as
`window.CS201_FIGURES`, so the film and the evidence-page generator read one mapping.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'homework': ROOT / 'data/summary.json',
    'midterm': ROOT / 'data/midterm-summary.json',
    'platform': ROOT / 'data/platform-summary.json',
}
FIGURES = ROOT / 'assets/app/figures.json'


def write_js(out, header, name, payload):
    body = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))
    out.write_text(f'// {header} Do not edit by hand.\nwindow.{name} = {body};\n')
    print(f'wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)')


def main():
    bundle = {key: json.loads(path.read_text()) for key, path in SOURCES.items()}
    write_js(ROOT / 'assets/app/data.js', 'Generated by scripts/build_app_data.py from data/*.json.', 'CS201', bundle)
    write_js(ROOT / 'assets/app/figures.js', 'Generated by scripts/build_app_data.py from assets/app/figures.json.',
             'CS201_FIGURES', json.loads(FIGURES.read_text()))


if __name__ == '__main__':
    main()
