"""Accessible explanations and aggregate tables for the midterm extension."""


def sections(d, table, figure):
    coverage = (f"{d['matched']} matched students from a {d['eligible_roster']}-member eligible roster; "
                f"{d['grades_not_in_excerpt']} grades were not in the supplied excerpt. "
                "This is a partial, non-random cohort, not the class grade distribution.")
    temporal = ("All selected homework windows end before the user-confirmed exam start."
                if d["pre_exam_verified"] else
                "Homework windows end on 15 September, 23:59 Beijing time. The exact exam start has not yet been confirmed, so these are homework–exam associations, not verified pre-exam predictors.")
    distribution = table(["Raw midterm points", "Students"],
                         [[r["label"], r["n"]] for r in d["distribution"]],
                         "Available Canvas excerpt only; unequal-width score categories.")
    correlation = table(["Behavior", "N", "Spearman ρ", "95% bootstrap interval", "Leave-one-out range"],
                        [[r["label"], r["n"], f"{r['rho']:+.3f}",
                          " to ".join(f"{v:+.3f}" for v in r["bootstrap_interval"]),
                          " to ".join(f"{v:+.3f}" for v in r["leave_one_out_range"])] for r in d["associations"]],
                        "Student-level correlations. Bootstrap intervals are unadjusted, exploratory and conditional on the observed sample.")
    sensitivity = table(["Behavior", "All matched", "All 23 problem slots attempted", "Without homework discrepancies"],
                        [[r["label"], f"{r['rho']:+.3f} (n={r['n']})",
                          f"{r['complete_problem_coverage']['rho']:+.3f} (n={r['complete_problem_coverage']['n']})",
                          f"{r['without_homework_discrepancies']['rho']:+.3f} (n={r['without_homework_discrepancies']['n']})"] for r in d["associations"]],
                        "Sensitivity subsets change cohort composition; they do not correct selection bias.")
    grouped = table(["Homework submissions", "N", "Mean exam", "Q1", "Median", "Q3"],
                    [[r["label"], r["n"], r["mean"], r["q1"], r["median"], r["q3"]] for r in d["attempt_groups"]],
                    "Middle 50% describes score dispersion; it is not a confidence interval.")
    html = f'''<section class="chart-section" id="midterm-distribution"><div class="section-heading"><span class="number">05</span><div><p class="eyebrow">MIDTERM / AVAILABLE SCORES</p><h2>A wider spread behind<br>near-perfect homework.</h2></div></div><p class="reading">The available midterm scores have a mean of <strong>{d['mean']:.2f}</strong> and median of <strong>{d['median']:.2f}</strong>. Canvas lists a nominal maximum of 100; values above 100 are preserved as raw points. No grade is capped or inferred.</p><p class="caution">{coverage}</p>'''
    html += figure("05-midterm-distribution", "Midterm score categories: 5 below 80, 5 from 80 to below 90, 10 from 90 to below 100, and 6 at 100 or above. 26 available grades.",
                   "Each bar counts students, not submissions. Categories have unequal widths and are not a density histogram. Every displayed group contains at least five students.")
    html += '<details><summary>Accessible data table · midterm distribution</summary>'+distribution+'</details></section>'
    html += f'''<section class="chart-section" id="midterm-associations"><div class="section-heading"><span class="number">06</span><div><p class="eyebrow">HOMEWORK PROCESS / EXAM OUTCOME</p><h2>Signals worth testing.<br>Not a prediction model.</h2></div></div><p class="reading">In this excerpt, final-day submission share has the clearest negative rank association with exam scores (<strong>ρ = {d['associations'][2]['rho']:+.2f}</strong>). Submission count is positively associated and mean first-submission score negatively associated, but both corresponding bootstrap intervals cross zero.</p><p>{temporal}</p>'''
    html += figure("06-midterm-associations", "Three Spearman correlations with 95 percent paired student bootstrap intervals; count and first-score intervals cross zero.",
                   "One observation per student. Dots show Spearman rank correlation; lines show 95% percentile intervals from 5,000 paired student bootstrap draws (fixed seed). These intervals do not account for non-random grade availability, unmeasured prior knowledge or multiple comparisons. No p-values or causal claims are made.")
    html += '<details><summary>Accessible data table · associations and sensitivity</summary>'+correlation+sensitivity+'</details>'
    html += '''<h3>What the three behaviors mean</h3><ul><li><strong>Submission count:</strong> all submissions inside each configured HW1–HW3 window, including attempts after acceptance.</li><li><strong>Mean first-submission score:</strong> first normalized score per attempted assignment–problem slot, then the mean within each student. Unattempted slots are not imputed as zero. Coverage varies, so a separate all-23-slots sensitivity check is shown.</li><li><strong>Final-24h share:</strong> the percentage of a student's in-window submissions made in the final 24 hours before that homework's configured deadline. It does not measure time spent studying or account for individual extensions.</li></ul><p class="caution">A first submission can follow off-platform work, and students may submit drafts at different stages. More submissions do not necessarily mean more effort; lower initial scores do not establish lower prior ability. The signs here are exploratory and can reflect cohort selection, problem coverage and different submission practices.</p></section>'''
    html += '''<section class="chart-section" id="midterm-attempt-groups"><div class="section-heading"><span class="number">07</span><div><p class="eyebrow">SUBMISSION GROUPS / SCORE DISPERSION</p><h2>The groups overlap.<br>Counts are not a target.</h2></div></div><p class="reading">Group means are <strong>81.00, 95.27 and 93.92</strong> for under 35, 35–59 and 60 or more submissions. The middle group has the highest mean, while the highest-count group has the highest median. A single summary cannot establish that additional attempts improve an exam score.</p>'''
    html += figure("07-midterm-attempt-groups", "Midterm score middle-50-percent bands for submission groups of 9, 11 and 6 students. Interquartile ranges overlap.",
                   "Bars span Q1–Q3; the line is the median and the diamond the mean. These are score-dispersion bands, not uncertainty intervals. Cutoffs are descriptive choices, not optimized thresholds, ability classifications or study recommendations. No individual points or extrema are published.")
    html += '<details><summary>Accessible data table · grouped scores</summary>'+grouped+'</details></section>'
    html += f'''<section class="next" id="midterm-plan"><p class="eyebrow">MIDTERM / SOURCES &amp; LIMITS</p><h2>Linked privately.<br>Reported in aggregate.</h2><p>{coverage} The available grades were transcribed from the user-provided Canvas excerpt and joined to unique same-name OJ course members, with homework scores cross-checked. Two homework discrepancies remain flagged; neither Canvas nor OJ values were altered. Excluding these two records leaves 24 students, as shown in the sensitivity table.</p><p>The OJ behavior extract was queried read-only on 21 September 2026. A named test account is excluded from this extension, leaving 41 eligible roster members. The original four figures retain their 20 September snapshot and 42-member non-staff roster denominator; the historical denominator includes that test account. The new behavior extract reconciles to the same 2,101 in-window submissions from 39 submitters; the 26 matched students contribute 1,507 of them.</p><p>{temporal} The user confirmed the exam began on 16 September 2026 at 12:00 Beijing time.</p><p>Individual grades, names, OJ identifiers and source linkage files stay outside the repository. The downloadable <a href="data/midterm-summary.json">midterm aggregate JSON</a> contains only cohort summaries. Groups have at least five students; this is disclosure reduction, not a formal anonymity guarantee. The remaining grades are needed before a complete cohort analysis; a prediction study would additionally need independent validation.</p><p><a href="docs/midterm-methods.md">Midterm methods and reproduction ↗</a></p></section>'''
    return html
