"""Evidence and accessible tables for the Course Pulse extension."""


def sections(d, table, figure):
    coverage = table(['Subset', 'Students'], [
        ['Eligible OJ roster', d['eligible_roster']], ['Available grades matched to Course Pulse', d['matched']],
        ['Of those: recorded pre-exam platform usage', d['recorded_users']],
        ['Of those: recorded resource opens', d['resource_users']]],
        'Nested subsets, not independent groups. No-record accounts remain in the 26-student analysis.')
    grouped = table(['Observed platform usage', 'N', 'Mean', 'Q1', 'Median', 'Q3'],
                    [[r[k] for k in ('label', 'n', 'mean', 'q1', 'median', 'q3')] for r in d['groups']],
                    'Raw exam points; middle 50% is score dispersion, not a confidence interval.')
    associations = table(['Behavior', 'N', 'Spearman ρ', '95% bootstrap interval'],
        [[r['label'], r['n'], f"{r['rho']:+.3f}", ' to '.join(f'{v:+.3f}' for v in r['bootstrap_interval'])]
         for r in d['oj_associations']+d['associations']],
        'Unadjusted, exploratory correlations; zero recorded activity is not zero study time.')
    sensitivity = table(['Platform metric', 'Main cutoff', 'Plus verified exam-morning cells'],
        [[r['label'], f"{r['rho']:+.3f}", f"{r['sensitivity_rho']:+.3f}"] for r in d['associations']],
        'Cells spanning the exam boundary are excluded in full; their pre-exam portion cannot be recovered.')
    html = '''<section class="chart-section" id="platform-coverage"><div class="section-heading"><span class="number">08</span><div><p class="eyebrow">COURSE PULSE / OBSERVATION COVERAGE</p><h2>A second window.<br>Not the whole learning process.</h2></div></div><p class="reading">All 26 available grade records have a unique normalized-name match to a Course Pulse student account. Of those, <strong>11 have recorded pre-exam platform activity</strong>, including nine with resource-open events. The other 15 have no observed activity in this tracking window; this does not establish that they did not study.</p><p>Personal tracking began on 8 September at 13:49 Beijing time. Main analysis ends on 16 September at 08:00, four hours before the exam, because metrics are aggregated by UTC day. OJ metrics span all three configured homework windows, so the sources cover different periods.</p>'''
    html += figure('08-platform-coverage', 'Nested coverage: 41 eligible roster members, 26 matched exam scores, 11 with platform records and nine with resource opens.', 'Personal observation begins late in the course. Grade availability is partial and non-random; these are coverage counts, not an adoption funnel over time.')
    html += '<details><summary>Accessible data table · coverage</summary>'+coverage+'</details></section>'
    html += '''<section class="chart-section" id="platform-groups"><div class="section-heading"><span class="number">09</span><div><p class="eyebrow">PLATFORM RECORDS / EXAM OUTCOMES</p><h2>A difference to investigate.<br>Not an effect to advertise.</h2></div></div><p class="reading">The 11 students with recorded activity average <strong>95.27</strong> points, compared with <strong>86.17</strong> among the 15 without a record. Their medians are 94.5 and 87.5. A 9.11-point difference between self-selected groups is not an estimate of what the platform caused.</p><p>Any positive recorded metric qualifies, including a brief visit. Students can download materials and study offline, use other tools, or differ in prior knowledge and motivation. These factors are not controlled here.</p>'''
    html += figure('09-platform-groups', 'Recorded-usage group: n=11, mean 95.27, median 94.5. No-record group: n=15, mean 86.17, median 87.5.', 'Bands show Q1–Q3, lines mark medians, and diamonds show means. No individual marks or extrema are published. Overlap and within-group dispersion matter alongside the means.')
    html += '<details><summary>Accessible data table · platform groups</summary>'+grouped+'</details></section>'
    html += '''<section class="chart-section" id="platform-associations"><div class="section-heading"><span class="number">10</span><div><p class="eyebrow">OJ + COURSE PULSE / SYNTHESIS</p><h2>Timing stands out.<br>Usage remains uncertain.</h2></div></div><p class="reading">Final-day OJ submission share remains negatively associated with exam scores. Platform active time, recorded days and resource opens each show positive rank associations, but <strong>all three platform intervals cross zero</strong>. These measures do not yet establish a reliable usage–achievement relationship.</p><p>Active time estimates foreground interaction, with an idle limit; it does not measure attention or total study time. Missing platform events are represented as zero recorded events only within the instrumented window. No claim is made about activity before tracking began.</p>'''
    html += figure('10-platform-associations', 'Five correlations in the same 26-person cohort. OJ final-day share is negative; all three platform bootstrap intervals include zero.', '5,000 paired-student bootstrap draws with a fixed seed. Intervals reflect resampling variability conditional on this sample, not selection bias. Metrics are correlated with one another and multiple comparisons are not adjusted. No predictive model or causal estimate is fitted.')
    html += '<details><summary>Accessible tables · correlations and cutoff sensitivity</summary>'+associations+sensitivity+'</details>'
    html += '''<h3>What the combined evidence supports</h3><p>Similar homework endpoints can conceal different submission schedules and resource-use patterns. In this partial cohort, concentrated final-day submissions accompany lower exam scores, while recorded platform users have higher average scores. Platform intensity remains uncertain, and prior ability, motivation and off-platform study could explain these patterns.</p><h3>Why AI and practice effectiveness are not plotted</h3><p>The export includes assistant replies, staff activity and messages that cannot be linked to current accounts. Linked student messages are concentrated on one date, and overlap with the available grade cohort is too small for a useful public comparison. Practice records are current draft snapshots, with no submitted outcomes; they cannot reconstruct edits, completed exercises or learning gains. These sources need further validation before effectiveness claims.</p><p class="caution">The next useful evidence is the remaining grades and a longer, consistently instrumented observation period. More variables alone will not resolve cohort selection or confounding.</p><p>Only real recorded usage is included; editable reported totals, demo accounts and staff activity are excluded. Raw CSVs, names, account IDs, messages and code remain outside the public repository. Public groups have at least five students; this reduces disclosure but is not a formal anonymity guarantee.</p><p><a href="data/platform-summary.json">Download platform aggregate JSON</a> · <a href="docs/platform-methods.md">Sources, definitions and reproduction ↗</a></p></section>'''
    return html
